### ISSUE TITLE
按钮拖拽到底部后，被底部菜单遮住

### ISSUE THREAD

**Issue by shijia2118** [Smueez/floating_animated_widget#1]
![floating_button](https://user-images.githubusercontent.com/45786044/176334564-a107f41d-9751-4fc2-bfe2-87781b7e4f0a.png)

**Comment by shijia2118** [comment]
遮住倒没关系，只是被遮住后，很难再把他拖拽出来。

**Comment by Smueez** [comment]
Hello,
I have checked your issue. Can you please describe to me in which
stuatuation this particular problem has acquired? Thank you.
Regards,
MD. Sheersho Mueez
email: ***@***.***

**Comment by Smueez** [comment]
Hello,
Have you used this widget on the top of bottomnavigation? If not then put
on the top of the widget chain. It will work then. Best will be that if you
put it on the top of the Scaffold widget. Hope it will work. But still
there is a problem . Please let me know. Thank you. Regards
