### ISSUE TITLE
Add FloatingDraggableAlign, Fix onDragging not call true

### ISSUE THREAD

**Issue by mhmmdadipur** [Smueez/floating_animated_widget#11]
Hello, I'm a beginner at flutter developer, I think I found one thing that doesn't work, namely "onDragging" doesn't return true when the widget is dragged. and I needed one thing namely align onlyLeft/onlyRight/both when "autoAlign = true" so I added that function. For more details, you can check the attached file. Thank You

[custom_floating_draggable_widget.zip](https://github.com/user-attachments/files/15845504/custom_floating_draggable_widget.zip)

**Comment by Smueez** [comment]
Thank you for this feedback.
The issue has been fixed.
And the new feature that has been mentioned here is added in the new version.
Happy coding <3
