### ISSUE TITLE
OnDragEvent with the current position of the the button

### ISSUE THREAD

**Issue by InspectlyMads** [Smueez/floating_animated_widget#12]
Summary:
It would be highly beneficial to have an OnDragEvent that provides access to the current position of the button as it is being dragged. This would allow for more control and flexibility when implementing drag-and-drop functionality.

Feature Details:

- Use Case: During drag-and-drop operations, it's often necessary to know the real-time position of the button or widget to update the UI accordingly, or to trigger specific actions depending on the location of the widget.
- Current Behavior: While there are existing events for drag interactions, they don’t currently provide the exact x/y coordinates or position updates of the button during the drag motion.
- Proposed Enhancement: Introduce an event, or extend the existing drag event system, to provide real-time position updates of the widget being dragged. This could be either the widget’s absolute position on the screen or relative to a parent widget.

Benefits:

1. Increased Control: Developers would be able to track the button's position dynamically and handle complex drag-and-drop layouts.
2. Improved UI Feedback: UI elements can react more fluidly to the drag action, providing better visual feedback for the user.
3. Custom Interactions: This allows for interactions such as snapping the button to certain areas or boundaries, highlighting target areas dynamically, or interacting with other draggable elements in real-time.

Example
`
onDragUpdate: (DragUpdateDetails details) 
{
  return details.localPosition;
}
`

**Comment by saalmi098** [comment]
+1 I’m also facing the same issue and would really appreciate having the feature to retrieve the position during or after dragging.

**Comment by Smueez** [comment]
Hello,
The new feature has been added in the new version. Please take a look. Thank you for this amazing feedback.
Happy coding
