### ISSUE TITLE
Remove print() statements

### ISSUE THREAD

**Issue by fhuonder** [Smueez/floating_animated_widget#3]
Could you remove the print statements?
Those are only useful for debugging. Maybe you could provide a flag to enable them. But by default they should be disabled.

Regards,
Florian

**Comment by Smueez** [comment]
Hello,
Thank you for your response. I will remove it so that it wont creates much
problem. thabk you. wait for the next update of this package. I will let
you know.
Regards,
Mueez

**Comment by fhuonder** [comment]
Great

Thank you...

**Comment by Smueez** [comment]
Hello,
I have removed all print(). Please update your package. Thank you
